/*
 * This source file was generated by the Gradle 'init' task
 */

 package  oop.week_1;

import java.util.Scanner;

public class App {

    // Fibonacci Sequence Program
    public static void fibonacciSequence() {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter n: ");
        int n = scanner.nextInt();
        
        if (n <= 0) {
            System.out.println("Please enter a positive integer greater than 0.");
            return;
        }

        int first = 1, second = 1;
        System.out.print(first + " " + second + " ");
        
        for (int i = 3; i <= n; i++) {
            int next = first + second;
            System.out.print(next + " ");
            first = second;
            second = next;
        }
        System.out.println();
    }

    // Matrix Multiplication Program
    public static void matrixMultiplication() {
        Scanner scanner = new Scanner(System.in);
        
        System.out.print("Enter the size of the matrix (n x n): ");
        int n = scanner.nextInt();

        int[][] matrix1 = new int[n][n];
        int[][] matrix2 = new int[n][n];
        int[][] result = new int[n][n];

        System.out.println("Fill in matrix 1:");
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                matrix1[i][j] = scanner.nextInt();
            }
        }

        System.out.println("Fill in matrix 2:");
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                matrix2[i][j] = scanner.nextInt();
            }
        }

        // Multiplying the matrices
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                result[i][j] = 0;
                for (int k = 0; k < n; k++) {
                    result[i][j] += matrix1[i][k] * matrix2[k][j];
                }
            }
        }

        System.out.println("Matrix 1:");
        printMatrix(matrix1);

        System.out.println("Matrix 2:");
        printMatrix(matrix2);

        System.out.println("Multiplication result:");
        printMatrix(result);
    }

    // Helper method to print matrices
    public static void printMatrix(int[][] matrix) {
        for (int[] row : matrix) {
            for (int value : row) {
                System.out.print(value + " ");
            }
            System.out.println();
        }
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Choose an option:\n1. Fibonacci Sequence\n2. Matrix Multiplication");
        int choice = scanner.nextInt();

        switch (choice) {
            case 1:
                fibonacciSequence();
                break;
            case 2:
                matrixMultiplication();
                break;
            default:
                System.out.println("Invalid choice");
        }
    }
}

